### ISSUE TITLE
Can not send out cmd firstly 

### ISSUE THREAD

**Issue by anka120** [DEWETRON/OXYGEN-SDK-SerialCsv#11]
In some usercases,the plugin send out cmd firtly,then the node send data.It does not work in that case.Only after the node send data ,the plugin can send cmd. Is there any way to solve this?

**Comment by anka120** [comment]
Setting variable of timeout works.
serial::Timeout t;
t.inter_byte_timeout = serial::Timeout::max();

**Comment by glaure** [comment]
Hi Anka,
Good that you found a solution for your problem!
Best regards,
Gunther
